- name: Ensure nginx package
  when: ansible_distribution == "Debian" or ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    name: nginx

- name: Ensure nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: reload nginx service

- name: Execute handlers
  ansible.builtin.meta: flush_handlers

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: started
