---
- name: Assert usage of systemd or upstart as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  ansible.builtin.command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  when: ansible_service_mgr == 'systemd'

- name: Set systemd version fact
  ansible.builtin.set_fact:
    vmselect_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"
  when: ansible_service_mgr == 'systemd'

- name: Check if vmselect is installed
  ansible.builtin.stat:
    path: /usr/local/bin/vmselect-prod
  changed_when: false
  check_mode: false
  register: vmselect_is_installed

- name: Check current vmselect version
  ansible.builtin.command: /usr/local/bin/vmselect-prod --version
  changed_when: false
  failed_when: false
  check_mode: false
  register: vmselect_current_version
  when: vmselect_is_installed.stat.exists | bool
