name: 'Lint'
on:
  pull_request: {}
  push: {}

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    container:
      image: python:3.9-alpine
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Setup ansible
        run: |
          apk add --update --no-cache --virtual build_dependencies gcc musl-dev libffi-dev openssl-dev rust cargo
          pip install --no-cache-dir ansible-core
          
          ansible-galaxy collection install community.general

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'roles'
          yamllint_strict: false
          yamllint_comment: false

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Ansible lint"
        uses: ansible/ansible-lint-action@v6.11.0
        with:
          args: "playbooks/*"
